# This workflow will verify the exercises in the repository.

name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  verify_exercises:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install Factor
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends g++ make wget
          git clone https://github.com/factor/factor.git /tmp/factor
          cd /tmp/factor
          git checkout cd14ceed53f6f9a43bbd3aec3950d8beb5439ed8
          ./build.sh update
          echo "/tmp/factor" >> $GITHUB_PATH

      - name: Install Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1'

      - name: Install Julia dependencies
        run: |
          cd generator
          julia --project=. -e 'using Pkg; Pkg.instantiate()'

      - name: Verify all exercises
        run: bin/verify-exercises
